### ISSUE TITLE
Error: localtunnel server returned an error, please try again

### ISSUE THREAD

**Issue by jamemackson** [localtunnel/localtunnel#121]
I am getting the below error when connecting using `lt --port 1776 --subdomain jame`  (version 1.8.1) I have a feeling the issue is with how our network/firewall is setup because everything works correctly when I'm not on my work network.  I can't find any documentation about what port configuration is needed.  Is this information documented anywhere?

Thanks in advance!

```bash
/usr/local/lib/node_modules/localtunnel/bin/client:48
        throw err;
        ^

Error: localtunnel server returned an error, please try again
    at Request._callback (/usr/local/lib/node_modules/localtunnel/lib/Tunnel.js:53:27)
    at Request.self.callback (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by jamemackson** [comment]
turns out the new firewall at work was blocking the tunnel traffic because it flagged it as IP Spoofing, go figure!  I think documenting what is required port wise might be good 👍 Great product though, thanks for making it!
