### ISSUE TITLE
Crashes unpredictably from time to time 

### ISSUE THREAD

**Issue by JemarJones** [localtunnel/localtunnel#122]
This seems to happen every once in a while, without explanation. It's quite disruptive.

```
>lt -p <mylocalport>
your url is: https://<mysubdomain>.localtunnel.me
/usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:46437 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1265:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Is this an issue with the tool or is my configuration incorrect?

**Comment by defunctzombie** [comment]
Please see other issues.

**Comment by JemarJones** [comment]
Which issue number(s) please?
