### ISSUE TITLE
unit test failed

### ISSUE THREAD

**Issue by calidion** [localtunnel/localtunnel#131]
```
git clone https://github.com/localtunnel/localtunnel.git
cd localtunnel/
npm install && npm test
```

```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
openurl@1.1.0 node_modules/openurl

debug@2.2.0 node_modules/debug
└── ms@0.7.1

yargs@3.29.0 node_modules/yargs
├── camelcase@1.2.1
├── y18n@3.2.1
├── decamelize@1.2.0
├── window-size@0.1.4
├── os-locale@1.4.0 (lcid@1.0.0)
└── cliui@3.2.0 (wrap-ansi@2.0.0, strip-ansi@3.0.1, string-width@1.0.1)

mocha@1.17.1 node_modules/mocha
├── diff@1.0.7
├── commander@2.0.0
├── growl@1.7.0
├── mkdirp@0.3.5
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

request@2.65.0 node_modules/request
├── tunnel-agent@0.4.3
├── aws-sign2@0.6.0
├── oauth-sign@0.8.2
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.5
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── tough-cookie@2.2.2
├── node-uuid@1.4.7
├── qs@5.2.1
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.11 (mime-db@1.23.0)
├── form-data@1.0.0-rc4 (async@1.5.2)
├── http-signature@0.11.0 (assert-plus@0.1.5, ctype@0.5.3, asn1@0.1.11)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── bl@1.0.3 (readable-stream@2.0.6)
└── har-validator@2.0.6 (pinkie-promise@2.0.1, commander@2.9.0, chalk@1.1.3, is-my-json-valid@2.13.1)

> localtunnel@1.8.1 test /home/live/localtunnel
> mocha --ui qunit --reporter list --timeout 10000 -- test/index.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

     setup local http server: local http on: 45045
  ․  setup local http server: 9ms
  1)  setup localtunnel client
  2)  query localtunnel server w/ ident
  3)  request specific domain
  4) --local-host localhost setup localtunnel client
  5) --local-host localhost override Host header with local-host
  6) --local-host 127.0.0.1 setup localtunnel client
  7) --local-host 127.0.0.1 override Host header with local-host
  8) --local-host 127.0.0.1 send chunked request

  1 passing (15s)
  8 failing

  1)  setup localtunnel client:
     Uncaught AssertionError: false == true
      at /home/live/localtunnel/test/index.js:26:16
      at /home/live/localtunnel/client.js:21:9
      at /home/live/localtunnel/lib/Tunnel.js:145:9
      at Request._callback (/home/live/localtunnel/lib/Tunnel.js:62:13)
      at Request.self.callback (/home/live/localtunnel/node_modules/request/request.js:198:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1082:10)
      at emitOne (events.js:82:20)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1009:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:921:12)
      at nextTickCallbackWith2Args (node.js:442:9)
      at process._tickCallback (node.js:356:17)

  2)  query localtunnel server w/ ident:
     TypeError: Parameter 'url' must be a string, not undefined
      at Url.parse (url.js:90:11)
      at Object.urlParse [as parse] (url.js:84:5)
      at Context.<anonymous> (/home/live/localtunnel/test/index.js:34:22)
      at Test.Runnable.run (/home/live/localtunnel/node_modules/mocha/lib/runnable.js:204:15)
      at Runner.runTest (/home/live/localtunnel/node_modules/mocha/lib/runner.js:374:10)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:452:12
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:299:14)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:309:7
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/home/live/localtunnel/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  3)  request specific domain:
     Uncaught AssertionError: false == true
      at /home/live/localtunnel/test/index.js:65:16
      at /home/live/localtunnel/client.js:21:9
      at /home/live/localtunnel/lib/Tunnel.js:145:9
      at Request._callback (/home/live/localtunnel/lib/Tunnel.js:62:13)
      at Request.self.callback (/home/live/localtunnel/node_modules/request/request.js:198:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1082:10)
      at emitOne (events.js:82:20)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1009:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:921:12)
      at nextTickCallbackWith2Args (node.js:442:9)
      at process._tickCallback (node.js:356:17)

  4) --local-host localhost setup localtunnel client:
     Uncaught AssertionError: false == true
      at /home/live/localtunnel/test/index.js:79:16
      at /home/live/localtunnel/client.js:21:9
      at /home/live/localtunnel/lib/Tunnel.js:145:9
      at Request._callback (/home/live/localtunnel/lib/Tunnel.js:62:13)
      at Request.self.callback (/home/live/localtunnel/node_modules/request/request.js:198:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1082:10)
      at emitOne (events.js:82:20)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1009:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:921:12)
      at nextTickCallbackWith2Args (node.js:442:9)
      at process._tickCallback (node.js:356:17)

  5) --local-host localhost override Host header with local-host:
     TypeError: Parameter 'url' must be a string, not undefined
      at Url.parse (url.js:90:11)
      at Object.urlParse [as parse] (url.js:84:5)
      at Context.<anonymous> (/home/live/localtunnel/test/index.js:87:22)
      at Test.Runnable.run (/home/live/localtunnel/node_modules/mocha/lib/runnable.js:204:15)
      at Runner.runTest (/home/live/localtunnel/node_modules/mocha/lib/runner.js:374:10)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:452:12
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:299:14)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:309:7
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/home/live/localtunnel/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  6) --local-host 127.0.0.1 setup localtunnel client:
     Uncaught AssertionError: false == true
      at /home/live/localtunnel/test/index.js:123:16
      at /home/live/localtunnel/client.js:21:9
      at /home/live/localtunnel/lib/Tunnel.js:145:9
      at Request._callback (/home/live/localtunnel/lib/Tunnel.js:62:13)
      at Request.self.callback (/home/live/localtunnel/node_modules/request/request.js:198:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1082:10)
      at emitOne (events.js:82:20)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/home/live/localtunnel/node_modules/request/request.js:1009:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:921:12)
      at nextTickCallbackWith2Args (node.js:442:9)
      at process._tickCallback (node.js:356:17)

  7) --local-host 127.0.0.1 override Host header with local-host:
     TypeError: Parameter 'url' must be a string, not undefined
      at Url.parse (url.js:90:11)
      at Object.urlParse [as parse] (url.js:84:5)
      at Context.<anonymous> (/home/live/localtunnel/test/index.js:131:22)
      at Test.Runnable.run (/home/live/localtunnel/node_modules/mocha/lib/runnable.js:204:15)
      at Runner.runTest (/home/live/localtunnel/node_modules/mocha/lib/runner.js:374:10)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:452:12
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:299:14)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:309:7
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/home/live/localtunnel/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  8) --local-host 127.0.0.1 send chunked request:
     TypeError: Parameter 'url' must be a string, not undefined
      at Url.parse (url.js:90:11)
      at Object.urlParse [as parse] (url.js:84:5)
      at Context.<anonymous> (/home/live/localtunnel/test/index.js:161:22)
      at Test.Runnable.run (/home/live/localtunnel/node_modules/mocha/lib/runnable.js:204:15)
      at Runner.runTest (/home/live/localtunnel/node_modules/mocha/lib/runner.js:374:10)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:452:12
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:299:14)
      at /home/live/localtunnel/node_modules/mocha/lib/runner.js:309:7
      at next (/home/live/localtunnel/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/home/live/localtunnel/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)



npm ERR! Test failed.  See above for more details.

```

**Comment by Coaxial** [comment]
If I checkout the last commit with [passing tests on Travis](https://travis-ci.org/localtunnel/localtunnel/builds/115349332) (i.e. `9a1d48764a167ae9fb05f42efdd7de0005e9edfc`, I can't get the tests to pass on my machine.

I have the same as above, 8 failures.

How could it pass on Travis but not locally for the same commit? I am also running the tests with node v4.
