### ISSUE TITLE
connection refused error

### ISSUE THREAD

**Issue by roccomuso** [localtunnel/localtunnel#169]
**Node version**: `v6.8.0`

Command launched: `lt -l 5000`

After a successfull 5.4Mb file transfer I got this error:

```
/usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:33765 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jnrfred** [comment]
@roccomuso Make sure your firewall is off

**Comment by roccomuso** [comment]
@jnrfred After a succesful transfer? it doesn't make much sense.

**Comment by jnrfred** [comment]
@roccomuso Ah! yeah very true. sorry, my bad.

**Comment by kagbodji** [comment]
appears to be a known issue, that maybe hasn't been fixed yet. see https://github.com/localtunnel/localtunnel/issues/81.  @Hacker432-Y550's suggested workaround works well for me:

```
#!/bin/bash

function localtunnel {
  lt -s subdomain --port port_number
}

until localtunnel; do
  echo "localtunnel server crashed"
  sleep 2
done
```

**Comment by yipcma** [comment]
any permanent fix, especially for cli?

**Comment by laukstein** [comment]
@kagbodji this isn't jet fixed, getting:

```
C:\Users\Admin\AppData\Roaming\npm\node_modules\localtunnel\bin\client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:41636 (check your firewall settings)
    at Socket.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:47:32)
    at Socket.emit (events.js:127:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by laukstein** [comment]
@kagbodji, @Hacker432-Y550 the workaround doesn't works for me - it keeps crashing forever.

**Comment by verboze** [comment]
Hmmm, I'm not sure then. Can you list processes and see if maybe there's a hanging localtunnel process still using the selected port? Can you try otherwise try starting localtunnel on a different port with `lt --port <some_port_num>` for instance?

**Comment by laukstein** [comment]
@verboze it get working now. Might be was *.localtunnel.me outages.

**Comment by defunctzombie** [comment]
Probably a localtunnel server outage.

**Comment by sosubramanian** [comment]
As a workaround, this bash script works well. I have been using it for a few days now.

````
#!/bin/bash
while true
	do
		echo "Building Local Tunnel"
		lt --subdomain DOMAIN_NAME --port PORT_NUMBER
	done
````

**Comment by happyduck** [comment]
@sokkalingam Thanks for your workaround solution. It works well for me. Just the loop doesn't stop even if it creates a tunnel successfully. Is there a way to break the loop if it is successful once.

**Comment by sokkalingam** [comment]
@happyduck I have updated my code, it should work the way you expect. Thanks.

**Comment by lilkersy** [comment]
Anyone still facing this issue in 2023?

**Comment by salmantln** [comment]
also facing the error issue 2024-03-31 16:19:34 iot-tunnel      | Error: connection refused: localtunnel.me:44967 (check your firewall settings)
2024-03-31 16:19:34 iot-tunnel      |     at Socket.<anonymous> (/usr/lib/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
2024-03-31 16:19:34 iot-tunnel      |     at Socket.emit (node:events:394:28)
2024-03-31 16:19:34 iot-tunnel      |     at emitErrorNT (node:internal/streams/destroy:193:8)
2024-03-31 16:19:34 iot-tunnel      |     at emitErrorCloseNT (node:internal/streams/destroy:158:3)
2024-03-31 16:19:34 iot-tunnel      |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by TheBoroer** [comment]
Should be fixed now!
