### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by rpelorosso** [localtunnel/localtunnel#235]
Hello,

I have installed localtunnel running 
```
npm -g install localtunnel
```
the install was successful, but running localtunnel generates the following error. I'm using node v0.10.26
Promise and Axios are installed.

```
/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/node_modules/axios/lib/core/Axios.js:40
  var promise = Promise.resolve(config);
                ^
ReferenceError: Promise is not defined
    at Axios.request (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/node_modules/axios/lib/core/Axios.js:40:17)
    at Axios.(anonymous function) [as get] (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/node_modules/axios/lib/core/Axios.js:61:17)
    at Function.wrap [as get] (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/node_modules/axios/lib/helpers/bind.js:9:15)
    at get_url (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/lib/Tunnel.js:44:15)
    at Tunnel._init (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/lib/Tunnel.js:67:7)
    at Tunnel.open (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/lib/Tunnel.js:139:10)
    at localtunnel (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/client.js:16:12)
    at Object.<anonymous> (/home/silencer/.nvm/v0.10.26/lib/node_modules/localtunnel/bin/client:53:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Do you have any idea on what could be going on?
 thank you!

**Comment by leim** [comment]
I think the problem is that your node version does not support promise. you can upgrade your node to the latest version, for example, node v8.x

**Comment by defunctzombie** [comment]
@leim is correct; you are using node 0.10.26 (as seen in the error backtrace) however this version is no longer supported.

A good enhancement to the CLI would be to read the node version and inform the user. Another possibility is for us to ship a CLI bundle which includes node pre-packaged.
