### ISSUE TITLE
Very sensitive to connection timing?

### ISSUE THREAD

**Issue by xmo-odoo** [localtunnel/localtunnel#255]
I'm running Little Snitch in Alert mode: every time an unknown software tries to connect from the machine to the outside, I get a popup asking whether the connection should be allowed and various configuration bits.

Localtunnel apparently doesn't like the delay of me pressing "return" and blows up with
```
your url is: https://weak-lion-73.localtunnel.me
/Users/masklinn/local/lib/node_modules/localtunnel/bin/client:65
        throw err;
        ^

Error: connection refused: localtunnel.me:36502 (check your firewall settings)
    at Socket.<anonymous> (local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```
if it's not configured as allowed (bypassing prompts).

I think it's the first software I've ever seen which was so sensitive to the LS prompt.

**Comment by laukstein** [comment]
I think localtunnel is discontinued, since in mostly doesn't work, regular outages for months.
Same issues here #169

**Comment by xmo-odoo** [comment]
@laukstein thanks for the answer, that would be disheartening as localtunnel looked like a useful alternative to ngrok's rate-limiting.

The error is the same as #169 but the *cause* is different, in #169 there's an issue as the transfer ends, in my case it reliably fails when the outbound firewall *delays* the request.

**Comment by viictorhgc** [comment]
I'm having the same problem, so I tried to migrate to ngrok, but I'm facing problems because I use tinyURL's api to shorten my URL's and for some reason it does not accept the URLs coming from ngrok ... Someone got some solution that at least restarts the service whenever it stops?
