### ISSUE TITLE
Problem with NodeJS and socket.io

### ISSUE THREAD

**Issue by Un-knownCoder** [localtunnel/localtunnel#277]
I'm creating a NodeJS server using socket.io for the comunication between server and clients, but when i search for the localtunnel autogenerated domain it fires me a 404 error for the file socket.io.js...
Is there a way to solve this problem?

```
Error: connection refused: localtunnel.me:43678 (check your firewall settings)
    at Socket.<anonymous> (C:\Users\@Username\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:47:32)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

> **@Username** refers to my PC username

**Comment by Un-knownCoder** [comment]
### Update:
The server only works sometimes, and when it doesn't work, it's because of the same problem as before...
😕😥
