### ISSUE TITLE
https://grumpy-newt-33.localtunnel.me

### ISSUE THREAD

**Issue by wanzetseO** [localtunnel/localtunnel#289]
/usr/local/lib/node_modules/localtunnel/bin/client:65
        throw err;
   

Error: connection refused: localtunnel.me:42261 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:1

**Comment by mrosenlund** [comment]
I'm always getting the same 👎

**Comment by przano** [comment]
Me as well. Same error

**Comment by defunctzombie** [comment]
Not enough info to debug - could be a number of causes - including a flaky localtunnel public server.
