### ISSUE TITLE
firewall settings

### ISSUE THREAD

**Issue by baptistapedro** [localtunnel/localtunnel#324]
I have a project working on localhost:8000
so i use the package to listen on -p 8000
then with the URL generated by `lt` I browse to it using my Android device.

After couple seconds localtunnel breaks
```
Error: connection refused: localtunnel.me:37371 (check your firewall settings)
    at Socket.<anonymous> (C:\Users\gitim\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:52:11)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

On my host where the app is running on localhost, the firewall settings are disabled for the network. Both the host running the app and the android device are using the same wifi network.

**Comment by DavidLJz** [comment]
@baptistapedro I'm having the same problem, can we  know how you got it solved on your end since you closed this issue?
