### ISSUE TITLE
Error: connection refused: localtunnel.me:46073

### ISSUE THREAD

**Issue by Articuno1234** [localtunnel/localtunnel#427]
C:\Users\User>lt --port 80
your url is: https://stale-shrimp-35.loca.lt
C:\Users\User\AppData\Roaming\npm\node_modules\localtunnel\bin\lt.js:81
    throw err;
    ^

Error: connection refused: localtunnel.me:46073 (check your firewall settings)
    at Socket.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:52:11)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by Articuno1234** [comment]
Nvm it was my Antivirus

**Comment by macleer** [comment]
what's the answer?
