### ISSUE TITLE
Cannot tunnel to local https server

### ISSUE THREAD

**Issue by introom** [localtunnel/localtunnel#460]
For the following command,
```npx localtunnel --port 443 --local-https --local-host www.google.com```

It will fail with:
```
your url is: https://cowardly-ladybug-74.loca.lt
node:internal/fs/utils:670
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at getLocalCertOpts (/Users/matthew/.npm/_npx/75ac80b86e83d4a2/node_modules/localtunnel/lib/TunnelCluster.js:79:24)
    at connLocal (/Users/matthew/.npm/_npx/75ac80b86e83d4a2/node_modules/localtunnel/lib/TunnelCluster.js:86:62)
    at Socket.<anonymous> (/Users/matthew/.npm/_npx/75ac80b86e83d4a2/node_modules/localtunnel/lib/TunnelCluster.js:149:7)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:402:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1143:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.2.0
```

**Comment by laemol** [comment]
Having the same issue here. Any solution on this?

**Comment by leafac** [comment]
Same issue here²

Setting `--allow-invalid-cert true` didn’t help.

Setting `--local-cert`, `--local-key`, and `--local-ca` didn’t help.

Any ideas of what could be going wrong?
