### ISSUE TITLE
Does not work with --local-https

### ISSUE THREAD

**Issue by hielfx** [localtunnel/localtunnel#472]
Hi all,

I have a local go server with https, using certificates generated by mkcert. https://localhost:4040 works fine.
When I try to use localtunnel with --local-https it gives the following error:
```bash
 lt --port 4040 --local-https
your url is: https://silent-donkey-6.loca.lt
node:internal/fs/utils:670
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at getLocalCertOpts (/Users/dsanchez/.nvm/versions/node/v16.13.0/lib/node_modules/localtunnel/lib/TunnelCluster.js:79:24)
    at connLocal (/Users/dsanchez/.nvm/versions/node/v16.13.0/lib/node_modules/localtunnel/lib/TunnelCluster.js:86:62)
    at Socket.<anonymous> (/Users/dsanchez/.nvm/versions/node/v16.13.0/lib/node_modules/localtunnel/lib/TunnelCluster.js:149:7)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:402:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1147:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

When I try to set the certficates path, it simply stops the program after generating the url:
```bash
lt --port 4040 --local-cert localhost.pem --local-key localhost-key.pem --local-https && echo "Stopped"
your url is: https://shaggy-snake-57.loca.lt
Stopped
```

If I do not set any of those, it displays "Client sent an HTTP request to an HTTPS server.".

I'm using Node v16.13.0 with nvm 0.34.0 on macOS Monterrey.

**Comment by HackerDaGreat57** [comment]
Same issue here.

**Comment by leafac** [comment]
Same issue here²

Adding `true` to the `--local-https` parameter didn’t help.

Setting `--local-cert`, `--local-key`, and `--local-ca` didn’t help.

Setting `--allow-invalid-cert true` didn’t help.

Any ideas of what could be going wrong?

**Comment by JanTrotnow** [comment]
It seems to be `--local_https` even though the options say `--local-https`.

**Comment by michaeldisaro** [comment]
> It seems to be `--local_https` even though the options say `--local-https`.

This is wrong, we have been stucked because localtunnel was not complaining about `--local_https` but it is just because localtunnel does not check for not recognized params and runs like they are not present.

Our solution has been: `lt --port <port> --subdomain <subdomain> --local-https --allow-invalid-cert`.

If you are using self signed certs you must use the combo `--local-https --allow-invalid-cert`.

The answer above misled us for some hours.

**Comment by vladrodin** [comment]
> > It seems to be `--local_https` even though the options say `--local-https`.
> 
> This is wrong, we have been stucked because localtunnel was not complaining about `--local_https` but it is just because localtunnel does not check for not recognized params and runs like they are not present.
> 
> Our solution has been: `lt --port <port> --subdomain <subdomain> --local-https --allow-invalid-cert`.
> 
> If you are using self signed certs you must use the combo `--local-https --allow-invalid-cert`.
> 
> The answer above misled us for some hours.

Worked for me

**Comment by BlueBayPhil** [comment]
The solution of appending --allow-invalid-cert did not work for me unfortunately :(

**Comment by ItsMeKoder** [comment]
Seems there is some issue with the names of the arguments and variables.
For e.g. the argument `--local-host` is actually refered by `argv.localHost`
So, I changed a few lines in the exec file.

If installed globally via `npm I -g localtunnel`, the exec file will be located in `/usr/local/lib/node_modules/localtunnel/bin/lt.js` file.

If not installed globally, it'll be `./node_modules/localtunnel/bin/lt.js`.

In the file change the following lines of code -

```node
.option('l', {                                            alias: 'localHost',                                     describe: 'Tunnel traffic to this host instead of l>  })                                                      .option('localHttps', {
    describe: 'Tunnel traffic to a local HTTPS server',
  })                                                      .option('localCert', {                                    describe: 'Path to certificate PEM file for local H>
  })
  .option('localKey', {
    describe: 'Path to certificate key file for local H>
  })
  .option('localCa', {
    describe: 'Path to certificate authority file for s>
  })
  .option('allowInvalidCert', {
    describe: 'Disable certificate checks for your loca>
  })
  .options('o', {                                           alias: 'open',
    describe: 'Opens the tunnel URL in your browser',
  })
  .option('printRequests', {
    describe: 'Print basic request info',
  })
  .require('port')
  .boolean('localHttps')
  .boolean('allowInvalidCert')
  .boolean('printRequests')
```

This seems to solve this issue for me.

_p.s. I am just a kid pls ignore any errors :)_

**Comment by ItsMeKoder** [comment]
Seems there is some issue with the names of the arguments and variables.
For e.g. the argument `--local-host` is actually refered by `argv.localHost`
So, I changed a few lines in the exec file.

If installed globally via `npm I -g localtunnel`, the exec file will be located in `/usr/local/lib/node_modules/localtunnel/bin/lt.js` file.

If not installed globally, it'll be `./node_modules/localtunnel/bin/lt.js`.

In the file change the following lines of code -

```node
.option('l', {                                            alias: 'localHost',                                     describe: 'Tunnel traffic to this host instead of l>  })                                                      .option('localHttps', {
    describe: 'Tunnel traffic to a local HTTPS server',
  })                                                      .option('localCert', {                                    describe: 'Path to certificate PEM file for local H>
  })
  .option('localKey', {
    describe: 'Path to certificate key file for local H>
  })
  .option('localCa', {
    describe: 'Path to certificate authority file for s>
  })
  .option('allowInvalidCert', {
    describe: 'Disable certificate checks for your loca>
  })
  .options('o', {                                           alias: 'open',
    describe: 'Opens the tunnel URL in your browser',
  })
  .option('printRequests', {
    describe: 'Print basic request info',
  })
  .require('port')
  .boolean('localHttps')
  .boolean('allowInvalidCert')
  .boolean('printRequests')
```

This seems to solve this issue for me.

_p.s. I am just a kid pls ignore any errors :)_

**Comment by PwccaCode** [comment]
its --local_host

**Comment by alitasawar** [comment]
try this  `netsh advfirewall set allprofiles state off` and whether or not it works turn it back on after u r done testing also make sure to add both  **--local-https** && **--allow-invalid-cert**

**Comment by cabello** [comment]
In my case it was a mismatch of underscores and dashes, once I put the right parameters it worked as expected, ideally it would print out something back saying it doesn't accept a given mistyped parameter:
```
npx localtunnel --port 3001 --local-https --local-cert "/Users/foo/project/localhost.pem" --local-key "/Users/foo/project/localhost-key.pem" --local-ca "/Users/foo/mkcert/rootCA.pem"  
```
Worked as expected
