### ISSUE TITLE
Error: Missing required argument #1

### ISSUE THREAD

**Issue by rsewell97** [localtunnel/localtunnel#477]
Hi, thanks in advance. 

I'm running Linux mint 19.1 and trying to install this using `npm`. I encounter the error `Error: Missing required argument #1` when following the instructions listed in the readme attached.

I've tried using the latest version of `npm==8.3.1` and `8.5.2`

Traceback printed below. 
```
$ npm install localtunnel

npm ERR! Linux 5.4.0-91-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "localtunnel"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/npm-debug.log
```

**Comment by wxyzed** [comment]
You have to update your nodejs

`sudo n stable`

**Comment by dheerajdlalwani** [comment]
Hi @rsewell97 ! Did you try it after updating NodeJS? If yes, did it work?
