### ISSUE TITLE
Support Android Server

### ISSUE THREAD

**Issue by evandrojr** [localtunnel/localtunnel#661]
I tried to use with termux and got this error:

```
~ $ lt --port 8080
/data/data/com.termux/files/usr/lib/node_modules/localtunnel/node_modules/openurl/openurl.js:16
        throw new Error('Unsupported platform: ' + process.platform);
        ^

Error: Unsupported platform: android
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/localtunnel/node_modules/openurl/openurl.js:16:15)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/localtunnel/bin/lt.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

Node.js v20.14.0

```

**Comment by evandrojr** [comment]
Adding lines 15 to 17 solved the problem for me:

![image](https://github.com/localtunnel/localtunnel/assets/939608/4a1b7fd7-e063-4253-82eb-ef251272bc21)
